# Generated by Django 4.0.3 on 2024-05-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qustion_id',
            new_name='question_id',
        ),
    ]
