# Generated by Django 4.0.3 on 2024-05-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
